In [3]:
import pandas as pd
import numpy as np

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet

from sklearn.preprocessing import StandardScaler

In [4]:
df_f = pd.read_csv('./Data/테슬라 총합 재무제표.csv', index_col=0)
df_f

,date,tesla,tesla_거래량,tesla_volatility,elec_fee,oil_price,oil_price_volatility,carbon_credits,carbon_credits_volatility,EVE종가,...,매출원가,매출총이익,영업이익,순이익,자산총계,매출총이익률,영업이익률,주당순이익EPS(달러),주가수익배수PER(배),총자산이익률ROA(%)
0,2015-01-02,43.86,23820.0,-1.39,6.67,52.69,-3.44,7.01,-3.31,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-01-05,42.02,26840.0,-4.20,6.67,50.04,-5.03,6.90,-1.57,13.38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015-01-06,42.26,31310.0,0.57,6.67,47.93,-4.22,6.77,-1.88,13.89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015-01-07,42.19,14840.0,-0.17,6.67,48.65,1.50,6.78,0.15,13.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015-01-08,42.12,17210.0,-0.17,6.67,48.79,0.29,6.81,0.44,13.80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1822,2022-02-28,870.43,32770.0,7.48,7.16,95.72,4.51,82.65,-5.83,89.50,...,40217.0,13606.0,6523.0,5519.0,62131.0,25.279156,12.119354,4.9,192.3,9.7
1823,2022-03-01,864.37,24720.0,-0.70,7.16,103.41,8.03,69.74,-15.62,86.90,...,40217.0,13606.0,6523.0,5519.0,62131.0,25.279156,12.119354,4.9,192.3,9.7
1824,2022-03-02,879.89,24650.0,1.80,7.16,110.60,6.95,67.72,-2.90,84.23,...,40217.0,13606.0,6523.0,5519.0,62131.0,25.279156,12.119354,4.9,192.3,9.7
1825,2022-03-03,839.29,20260.0,-4.61,7.16,107.67,-2.65,67.01,-1.05,79.51,...,40217.0,13606.0,6523.0,5519.0,62131.0,25.279156,12.119354,4.9,192.3,9.7
1826,2022-03-04,838.29,22390.0,-0.12,7.16,115.68,7.44,65.80,-1.81,78.15,...,40217.0,13606.0,6523.0,5519.0,62131.0,25.279156,12.119354,4.9,192.3,9.7

In [5]:
df_ = df_f.iloc[1027:]

In [6]:
df_ = df_.interpolate()

In [7]:
df_.tesla = df_.tesla.shift(-3)
df_.dropna(inplace=True)

In [8]:
df_

,date,tesla,tesla_거래량,tesla_volatility,elec_fee,oil_price,oil_price_volatility,carbon_credits,carbon_credits_volatility,EVE종가,...,매출원가,매출총이익,영업이익,순이익,자산총계,매출총이익률,영업이익률,주당순이익EPS(달러),주가수익배수PER(배),총자산이익률ROA(%)
1027,2019-01-02,66.99,58290.0,-6.82,6.58,46.54,1.42,26.57,1.03,8.37,...,17441.711111,4044.444444,-386.333333,-975.844444,29721.622222,18.824013,-1.798541,-1.14,-58.367778,-3.397778
1028,2019-01-03,67.07,34830.0,-3.14,6.58,47.09,1.18,24.52,-7.72,8.44,...,17453.066667,4045.666667,-385.500000,-975.766667,29712.433333,18.818938,-1.793846,-1.14,-58.271667,-3.396667
1029,2019-01-04,67.71,36970.0,5.78,6.58,47.96,1.85,24.90,1.55,8.38,...,17464.422222,4046.888889,-384.666667,-975.688889,29703.244444,18.813862,-1.789151,-1.14,-58.175556,-3.395556
1030,2019-01-07,68.99,37760.0,5.43,6.58,48.52,1.17,23.44,-5.86,8.50,...,17498.488889,4050.555556,-382.166667,-975.455556,29675.677778,18.798636,-1.775066,-1.14,-57.887222,-3.392222
1031,2019-01-08,69.45,35040.0,0.12,6.58,49.78,2.60,24.00,2.39,9.23,...,17509.844444,4051.777778,-381.333333,-975.377778,29666.488889,18.793561,-1.770371,-1.14,-57.791111,-3.391111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1819,2022-02-23,870.43,31070.0,-7.00,7.16,92.10,-0.27,94.74,5.69,89.08,...,40217.000000,13606.000000,6523.000000,5519.000000,62131.000000,25.279156,12.119354,4.90,192.300000,9.700000
1820,2022-02-24,864.37,44760.0,4.81,7.16,92.81,0.77,87.21,-7.95,85.99,...,40217.000000,13606.000000,6523.000000,5519.000000,62131.000000,25.279156,12.119354,4.90,192.300000,9.700000
1821,2022-02-25,879.89,25360.0,1.14,7.16,91.59,-1.31,87.77,0.64,89.35,...,40217.000000,13606.000000,6523.000000,5519.000000,62131.000000,25.279156,12.119354,4.90,192.300000,9.700000
1822,2022-02-28,839.29,32770.0,7.48,7.16,95.72,4.51,82.65,-5.83,89.50,...,40217.000000,13606.000000,6523.000000,5519.000000,62131.000000,25.279156,12.119354,4.90,192.300000,9.700000
1823,2022-03-01,838.29,24720.0,-0.70,7.16,103.41,8.03,69.74,-15.62,86.90,...,40217.000000,13606.000000,6523.000000,5519.000000,62131.000000,25.279156,12.119354,4.90,192.300000,9.700000

In [9]:
df_.columns

Index(['date', 'tesla', 'tesla_거래량', 'tesla_volatility', 'elec_fee',
       'oil_price', 'oil_price_volatility', 'carbon_credits',
       'carbon_credits_volatility', 'EVE종가', 'EVE거래량', 'EVE변동률', 'BYD종가',
       'BYD거래량', 'BYD변동률', 'DRIV종가', 'DRIV거래량', 'ACDC종가', 'ACDC거래량', 'kars',
       'kars_거래량', 'kars_volatility', 'batt', 'batt_거래량', 'batt_volatility',
       'PSI종가', 'PSI거래량', 'SOXX종가', 'SOXX거래량', 'SOXL종가', 'SOXL거래량', 'LIT조정종가',
       'LIT거래량', 'SGL종가', 'SGL변동률', 'li_price', 'co', 'co_volatility', '희토류가격',
       'nasdaq', 'nasdaq_거래량', 'nasdaq_volatility', 'ssec', 'ssec_거래량',
       'ssec_volatility', 'dollar', 'dollar_volatility', 'alu_price',
       'alu_vol', 'alu_change', 'cu_price', 'cu_change', 'REGI_price',
       'REGI_vol', 'REGI_change', 'snp_500', 'snp_500_volatility', 'kodex',
       'kodex_거래량', 'kodex_volatility', 'tiger', 'tiger_거래량',
       'tiger_volatility', 'tbx', 'tbx_거래량', 'tbx_volatility', '검색량', '매출액',
       '매출원가', '매출총이익', '영업이익', '순이익', '자산총계', '매출총이익률', '영업이익률',
       '주당순이익EPS(달러)', '주가수익배수PER(배)', '총자산이익률ROA(%)'],
      dtype='object')

In [12]:
#### 피쳐 => 변동률

y = df_['tesla']
x = df_[['tesla_volatility', 'oil_price_volatility', 'carbon_credits_volatility',\
       'EVE변동률', 'BYD변동률', 'SGL변동률', 'co_volatility', 'nasdaq_volatility',\
       'ssec_volatility', 'dollar_volatility', 'snp_500_volatility', 'kodex_volatility',\
       'tiger_volatility', 'tbx_volatility']]

In [13]:
x_train, x_test = x.iloc[:560], x.iloc[560:]
y_train, y_test = y.iloc[:560], y.iloc[560:]

In [18]:
# 스케일링

scaled = StandardScaler()
scaled.fit(x_train)
x_train_scaled = scaled.transform(x_train)
x_test_scaled = scaled.transform(x_test)

In [19]:
# LinearRegression 

lr = LinearRegression()
lr.fit(x_train_scaled, y_train)
preds_lr = lr.predict(x_test_scaled)
print('train :', lr.score(x_train_scaled,y_train))
print('test :', lr.score(x_test_scaled,y_test))

train : 0.057331901367184024
test : -10.887701932661265

In [20]:
# Ridge

train_score = []
test_score = []
alpha_list = list(np.arange(0.001, 100, 0.001))

for alpha in alpha_list:
    rid = Ridge(alpha=alpha)
    rid.fit(x_train_scaled, y_train)
    train_score.append(rid.score(x_train_scaled, y_train))
    test_score.append(rid.score(x_test_scaled, y_test))
    preds_rid = rid.predict(x_test_scaled)
print(train_score)
print(test_score)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [21]:
rid = Ridge(alpha=0.01)
rid.fit(x_train_scaled, y_train)
print(rid.score(x_train_scaled, y_train))
print(rid.score(x_test_scaled, y_test))

0.057331900046053375
-10.88765049536829

In [22]:
# Lasso

train_score = []
test_score = []
alpha_list = [0.001, 0.01, 0.1, 1, 10, 100]

for alpha in alpha_list:
    las = Lasso(alpha=alpha)
    las.fit(x_train_scaled, y_train)
    train_score.append(las.score(x_train_scaled, y_train))
    test_score.append(las.score(x_test_scaled, y_test))
    preds_las = las.predict(x_test_scaled)
print(train_score)
print(test_score)

[0.05733189878780298, 0.057331643301400836, 0.057306076117695004, 0.05476434114145157, 0.0398595235629452, 0.0]
[-10.887622831298199, -10.886911046834362, -10.879828775194113, -10.813134975973826, -10.842244260101948, -10.973167918615388]

In [23]:
las = Lasso(alpha=1)
las.fit(x_train_scaled, y_train)
preds = las.predict(x_test_scaled)
print(las.score(x_train_scaled, y_train))
print(las.score(x_test_scaled, y_test))

0.05476434114145157
-10.813134975973826

In [24]:
# ElasticNet

from sklearn.linear_model import ElasticNet

el= ElasticNet(alpha=10, l1_ratio=0.3)
el.fit(x_train_scaled, y_train)
preds_el = el.predict(x_test_scaled)
print(el.score(x_train_scaled, y_train))
print(el.score(x_test_scaled, y_test))

0.012052110532470017
-10.95429547120707